apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: argocd-redis
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  template:
    spec:
      nodeSelector:
        node-role.kubernetes.io/infra: ""