apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/v3.0.5/manifests/install.yaml

patches:
- path: patches/deployment-patches.yaml
  target:
    kind: Deployment
- path: patches/stateful-sets-patches.yaml
  target:
    kind: StatefulSet