apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-gateway-crds
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/jacktattersall1/homelab.git
    targetRevision: HEAD
    path: infrastructure/kustomizations/k8s-gateway-crds

  destination:
    name: in-cluster

  syncPolicy:
    automated:
      selfHeal: true
      prune: true