apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: keycloak-operator-crds
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/jacktattersall1/homelab.git
    targetRevision: HEAD
    path: infrastructure/kustomizations/keycloak-operator/crds

  destination:
    name: in-cluster
    namespace: keycloak-system

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true