apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metalb-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/jacktattersall1/homelab.git
    targetRevision: HEAD
    path: infrastructure/kustomizations/metalb

  destination:
    name: in-cluster
    namespace: metalb-system

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true

  ignoreDifferences:
    - group: infrastructure.cluster.x-k8s.io
      kind: AzureCluster
      jsonPointers:
        - /spec/networkSpec/subnets/0/natGateway/ip/name
        - /spec/networkSpec/subnets/0/natGateway/name
        - /spec/networkSpec/subnets/0/routeTable/name
        - /spec/networkSpec/subnets